- hosts: neo4j[0]
  tasks:
    - name: Generate new neo4j password
      action: update_pwsafe_credential
      args:
        project_id: "{{ pwsafe_project_id }}"
        credential_id: "{{ pwsafe_neo4j_credential_id }}"
      register: password_change

- hosts: neo4j
  tasks:
    - name: Neo4j - Update Password
      shell: echo "CALL dbms.security.changePassword('{{ neo4j_new_password }}');" | cypher-shell --non-interactive
      environment:
        NEO4J_USERNAME: "{{ neo4j_username }}"
        NEO4J_PASSWORD: "{{ neo4j_old_password }}"
      no_log: True
  vars:
    neo4j_old_password: "{{ neo4j_password }}"
    neo4j_new_password: "{{ hostvars[groups['neo4j'][0]]['password_change']['new_password'] }}"

# Update configuration for web services
- hosts: web
  roles:
    - web_install
  vars:
    cloud_snitch_web_neo4j_password: "{{ hostvars[groups['neo4j'][0]]['password_change']['new_password'] }}"

# Update configuration for sync services.
- hosts: cloud_snitch_sync
  roles:
    - sync_install
  vars:
    cloud_snitch_neo4j_password: "{{ hostvars[groups['neo4j'][0]]['password_change']['new_password'] }}"
