- name: Find all .tar.gz
  find:
    path: "{{ cloud_snitch_data_dir }}"
    file_type: file
    recurse: yes
    patterns: '*.tar.gz'
  register: dataarchives
  tags:
    - sync

- name: Remove archives
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ dataarchives.files }}"
  tags:
    - sync
