- name: restart auditd
  service:
    name: auditd
    state: restarted

- name: generate auditd rules
  command: augenrules --load
  notify: restart auditd

- name: restart splunk
  become: yes
  become_user: splunk
  command: ./splunk restart
  args:
    chdir: /opt/splunkforwarder/bin
