---
- name: Get Openstack Release Data
  openstack_release:
  register: osa_details

- name: Run snitch collector - Newton +
  become: yes
  command: "openstack-ansible snitch.yml --forks {{ cloud_snitch_forks }}"
  environment:
    CLOUD_SNITCH_ENABLED: true
    CLOUD_SNITCH_CONF_FILE: "{{ cloud_snitch_conf_file }}"
    CLOUD_SNITCH_CRYPT_ENABLED: "{{ cloud_snitch_crypt_enabled }}"
    CLOUD_SNITCH_CRYPT_KEY: "{{ crypto_aes_key }}"
    CLOUD_SNITCH_RUN_ID: "{{ run_id }}"
    CLOUD_SNITCH_ENVIRONMENT_ACCOUNT_NUMBER: "{{ cloud_snitch_environment_account_number }}"
    CLOUD_SNITCH_ENVIRONMENT_NAME: "{{ cloud_snitch_environment_name }}"
    CLOUD_SNITCH_ENVIRONMENT_UUID: "{{ cloud_snitch_environment_uuid }}"
  ignore_errors: yes
  args:
    chdir: "{{ cloud_snitch_playbook | dirname }}"
  tags:
    - collect
  when: osa_details.major_release and osa_details.major_release >= 14
  async: "{{ cloud_snitch_collection_timeout }}"
  poll: "{{ cloud_snitch_collection_poll }}"

- name: Run snitch collector - Mitaka -
  become: yes
  command: "openstack-ansible snitch.yml --forks {{ cloud_snitch_forks }}"
  environment:
    CLOUD_SNITCH_ENABLED: true
    CLOUD_SNITCH_CONF_FILE: "{{ cloud_snitch_conf_file }}"
    CLOUD_SNITCH_CRYPT_ENABLED: "{{ cloud_snitch_crypt_enabled }}"
    CLOUD_SNITCH_CRYPT_KEY: "{{ crypto_aes_key }}"
    CLOUD_SNITCH_RUN_ID: "{{ run_id }}"
    CLOUD_SNITCH_ENVIRONMENT_ACCOUNT_NUMBER: "{{ cloud_snitch_environment_account_number }}"
    CLOUD_SNITCH_ENVIRONMENT_NAME: "{{ cloud_snitch_environment_name }}"
    CLOUD_SNITCH_ENVIRONMENT_UUID: "{{ cloud_snitch_environment_uuid }}"
    ANSIBLE_INVENTORY: "{{ cloud_snitch_inventory_locations | join(':') }}"
    ANSIBLE_SSH_PIPELINING: "True"
    ANSIBLE_HOST_KEY_CHECKING: "False"
  ignore_errors: yes
  args:
    chdir: "{{ cloud_snitch_playbook | dirname }}"
  tags:
    - collect
  when: osa_details.major_release and osa_details.major_release < 14
  async: "{{ cloud_snitch_collection_timeout }}"
  poll: "{{ cloud_snitch_collection_poll }}"

- name: Archive the dataset
  become: yes
  archive:
    path: "{{ cloud_snitch_data_dir }}/{{ run_id }}"
    dest: "{{ cloud_snitch_data_dir }}/{{ run_id }}.tar.gz"
    exclude_path:
      - "{{ cloud_snitch_data_dir }}"
    format: gz
  tags:
    - collect

- name: Fetch the dataset
  fetch:
    src: "{{ cloud_snitch_data_dir }}/{{ run_id }}.tar.gz"
    dest: "{{ cloud_snitch_data_dir }}/{{ run_id }}.tar.gz"
    fail_on_missing: false
    flat: yes
  tags:
    - collect

- name: Sync the dataset
  action: sync
  args:
    uuid: "{{ run_id }}"
    key:  "{{ crypto_aes_key }}"
  tags:
    - collect

- name: Remove archive
  become: yes
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ cloud_snitch_data_dir }}/{{ run_id }}.tar.gz"
    - "{{ cloud_snitch_data_dir }}/{{ run_id }}"
  tags:
    - collect
